// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStudent(arg1) {
  return window['go']['main']['App']['AddStudent'](arg1);
}

export function DeleteStudent(arg1) {
  return window['go']['main']['App']['DeleteStudent'](arg1);
}

export function ExportStudentsToExcel(arg1, arg2) {
  return window['go']['main']['App']['ExportStudentsToExcel'](arg1, arg2);
}

export function GetStageCounts() {
  return window['go']['main']['App']['GetStageCounts']();
}

export function GetStudents(arg1, arg2) {
  return window['go']['main']['App']['GetStudents'](arg1, arg2);
}

export function ImportStudentsFromExcel(arg1) {
  return window['go']['main']['App']['ImportStudentsFromExcel'](arg1);
}

export function ParseNationalID(arg1) {
  return window['go']['main']['App']['ParseNationalID'](arg1);
}
