// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddStudent(arg1:models.Student):Promise<models.Student>;

export function DeleteStudent(arg1:string):Promise<void>;

export function ExportStudentsToExcel(arg1:string,arg2:string):Promise<void>;

export function GetStageCounts():Promise<Record<string, number>>;

export function GetStudents(arg1:string,arg2:string):Promise<Array<models.Student>>;

export function ImportStudentsFromExcel(arg1:string):Promise<Array<models.Student>>;

export function ParseNationalID(arg1:string):Promise<models.NIDData>;
